services:
  api:
    image: home-coffing-api:${API_IMAGE_TAG:-latest}
    container_name: home-coffing-api
    restart: unless-stopped
    ports:
      - '3011:3001'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
