services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      HOME_INVENTORY_DB_PASSWORD: ${HOME_INVENTORY_DB_PASSWORD}
      HOME_COFFING_DB_PASSWORD: ${HOME_COFFING_DB_PASSWORD}
    volumes:
      - ~/.db/mysql:/var/lib/mysql
      - ../db/scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - ~/.db/redis:/data
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      AI_LIFE_COACH_DB_PASSWORD: ${AI_LIFE_COACH_DB_PASSWORD}
    volumes:
      - ~/.db/postgres:/var/lib/postgresql/data
      - ../db/postgres-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

