services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      HOME_INVENTORY_DB_PASSWORD: ${HOME_INVENTORY_DB_PASSWORD}
      HOME_COFFING_DB_PASSWORD: ${HOME_COFFING_DB_PASSWORD}
    volumes:
      - ~/.db/mysql:/var/lib/mysql
      - ../db/scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - ~/.db/redis:/data
    ports:
      - "6379:6379"

